language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 240s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: zGpsGhbBxf4exIPeTuCDTYM804uQjCoteKNwNX7O2Kjy2LnYfqYOrpeRXegkalGRYJfXcdnZDSrJtYCN/Gs5rX/iADlI16PUiFHb2fVX58WS9nEpXG1PkfgGp72BNzFrpjXQ5c+piuiqnVwcdzi3eqvJ34jpX+6S+FMDdLfG82NlMcop6eAdTpejnCzcEtoLjsSiRZaOEeozTBU+QNR91MNuyXS96FIx7hGS/DBsbnhQLaFJ4bEnczfre+gBAQefo3fJCQi9FdGL35TO1XLBe8mfLHBLDcqKO0in5lWZbivW2gia7UBR02hs+G5cSYg2fxudOWlUbWPBPI7j5txWqHPO7phDGOAzilQMg+gXiKTCmn8pZYS4yKUhHuH11iIa4J9dhfthQzYF/OMrqf7W8BSbUvb0m18tBgFW2KGeC8B/1ZsVSkwdNX09IQPRux32Wb35x/yxLe36qPpVG0pZzSlUupOCQYIzWZIczqsChXtipQpTAgY1/FDI+8hf/GdqYarmCONecULeIcgCWUJbdX2n8qD+advoLgQCfv/tcfkhCNfZvUqKGMoWi5qJVKg66ebEaNNsDZjVIoRYa3pH1f84EJMQ2fHcoZ6VDo1Pw7zfzSPZ12+DuasH0K6BKc/0R3wCanDOAWb5emckZNYmp6GPwvgn+XceMXlteLEV9Ck=
    on_success: always
